version: '3'
services:
    instagram-bot:
      container_name: instagram-bot
      build: .
      env_file: .env
      volumes:
        - .:/app
      ports:
       - 3000:3000
      networks:
       - common
    mongo:
      container_name: mongo
      image: mongo
      env_file:
        - .env
      volumes:
        - ./data/mongo1:/data/db
      networks:
        - common
      ports:
        - 27017:27017
networks:
  common:
    driver: bridge
     